name: Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Client image
        run: |
          docker login --username ${{ github.actor }} --password ${{ secrets.GIT_TOKEN }} ghcr.io
          docker build ./client --file ./client/Dockerfile --tag ghcr.io/faklor/oli-sykes:latest
          docker push ghcr.io/faklor/oli-sykes:latest
